GCN:
  pubmed:
    lr: 0.001
    wd: 1e-7
    erase_ratio: 0.01 
    l: 0.3
  cora:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
  citeseer:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
  CS:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
  Physics:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
  ogbn-arxiv:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
GAT:
  pubmed:
    lr: 0.001
    wd: 1e-7
    erase_ratio: 0.01 
    l: 0.3
  cora:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.03 
    l: 0.7
  citeseer:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
  CS:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
  Physics:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
  ogbn-arxiv:
    lr: 0.001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
GIN:
  pubmed:
    lr: 0.0001
    wd: 1e-7
    erase_ratio: 0.01 
    l: 0.3
  cora:
    lr: 0.0001
    wd: 1e-4
    erase_ratio: 0.01
    l: 0.3
  citeseer:
    lr: 0.0001
    wd: 1e-4
    erase_ratio: 0.01 
    l: 0.3
  CS:
    lr: 0.0001
    wd: 1e-6
    erase_ratio: 0.01 
    l: 0.01
  Physics:
    lr: 0.0001
    wd: 1e-4
    erase_ratio: 0.03 
    l: 0.001
SAGE:
  pubmed:
    lr: 0.0001
    wd: 1e-6
    erase_ratio: 0.01 
    l: 0.01
  cora:
    lr: 0.0001
    wd: 1e-6
    erase_ratio: 0.01
    l: 0.3
  citeseer:
    lr: 0.0001
    wd: 1e-6
    erase_ratio: 0.01 
    l: 0.3
  CS:
    lr: 0.0001
    wd: 1e-6
    erase_ratio: 0.01 
    l: 0.01
  Physics:
    lr: 0.0001
    wd: 1e-4
    erase_ratio: 0.03 
    l: 0.001